name: CI

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ci.yml'

jobs:

  lint:
    name: Ruff lint
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.11'
          - '3.12'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python-version }}"
          cache: 'pip'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.8"
      - name: Install the project
        run: 'uv sync --locked --all-extras --dev'
      - name: Lint with Ruff
        run: 'uv run ruff check .'

  format:
    name: Ruff format
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.11'
          - '3.12'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python-version }}"
          cache: 'pip'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.8"
      - name: Install the project
        run: 'uv sync --locked --all-extras --dev'
      - name: Format with Ruff
        run: 'uv run ruff format .'

