name: Tests

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/tests.yml'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/tests.yml'

jobs:
  tests:
    name: Tests
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.11'
          - '3.12'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
          cache: 'pip'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.8"
      - name: Install dependencies
        run: 'uv sync --locked --all-extras --dev'
      - name: Run tests
        run: 'uv run pytest tests -s --cov --cov-report=xml'
      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
          files: coverage.xml
          slug: firelink-sh/evolve-py
          fail_ci_if_error: true

